export const SITE_CONFIG = {
  OWNER_NAME: "TEST",
  LEGAL_ADDRESS: "TEST",
  FISCAL_CODE: "TEST",
  CONTACT_EMAIL: "TEST",
  PRIVACY_EMAIL: "TEST",
  ABUSE_EMAIL: "TEST",
  DOMAIN: "domrentals.com",
  COOKIE_RETENTION_MONTH: 12,
  ANALYTICS_RETENTION_MONTHS: 26,
  LAST_UPDATED: "October 2025",
  JURISDICTION_CITY: "Bologna",
  COUNTRY: "Italy",
  PAGE_TITLE: "domrentals",
  PAGE_DESCRIPTION: "Maximize Your Rental Revenue. Showcase Your Property With Us.",
  MONTHLY_PRICE: "20€",
  CONTACT_PHONE:"+39 3452754245",
  CONTACT_WHATSAPP_LINK: "https://wa.me/00393452754245"
}
